name: POE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ Main ]
  pull_request:
    branches: [ Main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
     # list contents or directory
      - name: List contents
        run: ls
     # Compiles classes to test 
      - name: compile classes
        working-directory: ./src
        run: javac -cp "../lib/junit-platform-console-standalone-1.6.0.jar" ./main/java/com/POE/startup/PartOne.java ./main/java/com/POE/startup/Login.java  "../src/test/java/com/POE/startup/LoginTest.java" "../src/main/java/com/POE/startup/Login.java"    

    # list contents of src to verify that classess compiled 
      - name: List contents of src directory after compile
        working-directory: ./src/main/java/com/POE/startup
        run: ls
        
        
       # copy compiled classes to test directory 
      - name : copy compiled classes to testresources directory 
        working-directory: ./src
        run: cp -t ./test/java/com/POE/startup ./main/java/com/POE/startup/Login.class ./main/java/com/POE/startup/PartOne.class
        
        #copy compiled tests 
      - name : copy compiled Test classes to testresources directory 
        working-directory: ./src
        run: cp -t  ./test/java/com/POE/startup ./main/java/com/POE/startup/Login.class ./main/java/com/POE/startup/PartOne.class
        
        # list contents or directory
      - name: List contents test package
        working-directory: ./src/test/java/com/POE/startup
        run: ls
        
        #run Login Class tests and output report 
      - name: run Login Class tests and create report 
        working-directory: ./src
        run: |
         ls
         java -jar  "../lib/junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class  test/java/com/POE/startup.LoginTest.java
         

